module-name: kyma-companion
kind: kcp
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-companion:main
checkmarx-one:
  preset: python-default
  exclude:
    - "tests/**"
    - "**/tests/**"
mend:
  language: python
  exclude:
    - "tests/**"
    - "**/tests/**"
