name: Validate Model Evaluator

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

jobs:
  model-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/blackbox
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Python version
        id: python-version
        run: ./../../scripts/shell/extract-python-version.sh

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Run Evaluator Validation
        run: |
          export CONFIG_PATH=$GITHUB_WORKSPACE/config/config.json
          echo "${{ secrets.EVALUATION_TESTS_CONFIG }}" | base64 --decode | jq > $CONFIG_PATH
          echo "saved config to $CONFIG_PATH!"
          poetry run python src/run_validation.py
